
pipeline {
    agent any

    environment {
        MAVEN_HOME = '/usr/share/maven'
        JAVA_HOME = '/usr/lib/jvm/java-17-openjdk-amd64'  // Ensure this matches your Java installation
        PATH = "${MAVEN_HOME}/bin:${JAVA_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'dev',
                    credentialsId: 'shilpay25',
                    url: 'https://github.com/shilpay25/mern-admin/tree/6b17ecfe8a020ecab2fbfe59cd61961e4c5897a5/frontend'
            }
        }

        stage('Maven Clean Package') {
            steps {
                dir('Frontend') {
                    sh 'mvn clean package -DskipTests=true'
                }
            }
        }

        stage('Docker Build Test Container') {
            steps {
                script {
                    // Build Docker image for testing with the current build number as a tag
                    sh 'docker build --no-cache -t shilpay25/mern-admin:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Run Tests in Docker Container') {
            steps {
                script {
                    // Run the Docker container with Maven tests
                    sh '''docker run -d -p 2000:3000 \
                    -v "${WORKSPACE}:/workspace" -w /workspace \
                    shilpay25/mern-admin:${BUILD_NUMBER} sh -c "/usr/share/maven \
                    -Dtest=Tests.SignUpTests clean test"'''
                }
            }
        }
        
        stage('Docker Run Production Container') {
            steps {
                script {
                    // Run the production container and map to port 3000
                    sh 'docker run --name shilpay25 -d -p 3000:3000 shilpay25/mern-admin:${BUILD_NUMBER}'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Investigating...'
        }
    }
}
